### ISSUE TITLE
Missing .htaccess for Apache servers

### ISSUE THREAD

**Issue by 7rust** [JustSteveKing/SlimBootstrap#1]
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]

in /web

**Comment by JustSteveKing** [comment]
Ah my bad! Thank you, would you like to add a pull request and I will merge??

**Comment by JustSteveKing** [comment]
I have now added this into the `web` directory
